import type { Metadata } from 'next';
import { Plus_Jakarta_Sans, Geist } from 'next/font/google';
import cn from '@/shared/lib/utils/cn';
import './globals.css';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'ClientFlow',
  description: 'CRM generated by Sandro Moraes',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={cn(
        plusJakartaSans.variable,
        'h-full',
        'antialiased',
        'font-sans',
        geist.variable,
      )}
    >
      <body className={cn('min-h-full', 'flex', 'flex-col')}>
        <div vaul-drawer-wrapper='' className='bg-background'>
          {' '}
          {children}{' '}
        </div>
      </body>
    </html>
  );
}
